import { NextResponse } from 'next/server'
import type { Part, PartType } from '@/lib/types'
import { uid, sleep } from '@/lib/utils'
import { getPartType } from '@/lib/parts'
import { getTransform } from '@/lib/transforms'

export async function POST(request: Request) {
  try {
    const { sourcePart, targetType }: { sourcePart: Part; targetType: PartType } =
      await request.json()

    // Validate transform
    const transform = getTransform(sourcePart.type, targetType)
    if (!transform) {
      return NextResponse.json(
        { error: 'Invalid transform' },
        { status: 400 }
      )
    }

    // Mock generation (Task 3.2)
    await sleep(2000) // Simulate API delay

    const targetMeta = getPartType(targetType)
    const mockContent = generateMockContent(sourcePart, targetType, transform.transformType)

    const newPart: Part = {
      id: uid(),
      projectId: '', // Unsaved initially
      type: targetType,
      title: `${targetMeta.name} (from ${sourcePart.title})`,
      content: mockContent,
      metadata: {
        wordCount: mockContent.split(/\s+/).length,
        sourcePartId: sourcePart.id,
        transformType: transform.transformType,
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }

    return NextResponse.json(newPart)
  } catch (error) {
    console.error('Transform error:', error)
    return NextResponse.json(
      { error: 'Transform failed' },
      { status: 500 }
    )
  }
}

// Mock content generator - uses intelligent templates for all 60 part types
function generateMockContent(
  sourcePart: Part,
  targetType: PartType,
  transformType: string
): string {
  const snippet = sourcePart.content.slice(0, 200)
  const targetMeta = getPartType(targetType)

  // Generic template based on category and transform type
  const header = `[${transformType.toUpperCase()} TRANSFORM]\n${targetMeta.icon} ${targetMeta.name}\n\nGenerated from: ${sourcePart.title}\n\n---\n\n`

  const footer = `\n\n---\n\n[This is mock content. In production, this will be generated by AI based on the source material and target format requirements.]`

  // Category-specific content structure
  switch (targetMeta.category) {
    case 'text-foundations':
      return `${header}FOUNDATION ELEMENT\n\n${snippet}\n\n[Additional ${targetMeta.name.toLowerCase()} elements would be extracted and structured here...]${footer}`

    case 'short-form':
      return `${header}SHORT-FORM CONTENT (${targetMeta.wordCount.min}-${targetMeta.wordCount.max} words)\n\n${snippet.slice(0, 150)}\n\n[Hook, body, and CTA optimized for ${targetMeta.name}...]${footer}`

    case 'long-form':
      return `${header}LONG-FORM CONTENT\n\n${snippet}\n\n## Section 1\n[Expanded context and setup...]\n\n## Section 2\n[Rising action and development...]\n\n## Section 3\n[Climax and resolution...]${footer}`

    case 'video-production':
      return `${header}VIDEO PRODUCTION DOCUMENT\n\nBased on source material:\n${snippet}\n\n[Production-specific formatting for ${targetMeta.name} would appear here with technical specifications, timing, and visual direction...]${footer}`

    case 'audio-production':
      return `${header}AUDIO PRODUCTION DOCUMENT\n\nSource material:\n${snippet}\n\n[Audio-specific formatting for ${targetMeta.name} with timing cues, sound design notes, and pacing guidelines...]${footer}`

    case 'marketing':
      return `${header}MARKETING CONTENT\n\n${snippet}\n\n[Conversion-optimized copy for ${targetMeta.name} with CTAs, social proof, and benefit-focused messaging...]${footer}`

    default:
      return `${header}${snippet}\n\n[Generated ${targetMeta.name} content would appear here...]${footer}`
  }
}
