import OpenAI from 'openai'
import { zodResponseFormat } from 'openai/helpers/zod'
import { z } from 'zod'
import type { AIReviewResult, ReviewOutputParams } from '@/lib/types'
import { env } from '@/lib/env'
import { startLangfuseGeneration } from '@/lib/billing/langfuse'

/**
 * OpenAI adapter for AI-powered content review (admin-only)
 * Uses GPT-5.4 — the most capable model — for analytical quality assessment
 */

const openai = new OpenAI({
  apiKey: env.openai.apiKey,
})

// ========================================
// Zod Schema for Structured Review Output
// ========================================

const RubricAnalysisSchema = z.object({
  rubric: z.string().describe('Name of the quality dimension being assessed'),
  score: z.number().describe('Score from 1-10 for this rubric'),
  analysis: z.string().describe('Detailed assessment with specific evidence quoted from the story. 2-4 sentences explaining the score.'),
})

const RubricScoreSchema = z.object({
  rubric: z.string().describe('Name of the quality dimension'),
  score: z.number().describe('Score from 1-10'),
})

const ReviewResponseSchema = z.object({
  rubricAnalyses: z.array(RubricAnalysisSchema).describe('Detailed rubric-by-rubric analysis with evidence'),
  overallGrade: z.string().describe('Overall letter grade A-F'),
  verdict: z.string().describe('One concise sentence summarizing the overall quality'),
  rubricScores: z.array(RubricScoreSchema).describe('Crisp rubric name + score pairs for at-a-glance scanning'),
  weaknesses: z.array(z.string()).describe('Top weaknesses to address via prompt enhancement — specific and actionable'),
  strengths: z.array(z.string()).describe('Top strengths to preserve when modifying prompts — specific and evidence-based'),
  promptSuggestions: z.array(z.string()).describe('Specific, actionable prompt modifications the admin could make to improve output quality'),
  additionalNotes: z.array(z.string()).describe('Any other observations valuable to an admin reviewer — edge cases, patterns, or meta-observations'),
})

// ========================================
// Review System Prompt (XML Framework)
// ========================================

function buildReviewSystemPrompt(): string {
  return `<role>
You are an elite editorial reviewer and prompt engineer with deep expertise in:
- Creative writing quality assessment across platforms (Reddit, TikTok, YouTube, marketing)
- AI-generated content detection and authenticity analysis
- Prompt engineering — understanding how prompt structure, constraints, and role definitions affect output quality
- Narrative craft — story structure, pacing, voice, hook effectiveness, emotional resonance

You operate at the level of a senior content strategist at a top publishing house who also has deep technical understanding of LLM prompt mechanics. Your reviews are used by admin reviewers to systematically improve prompt templates and generation quality.
</role>

<context>
You are reviewing content generated by StoryWeaver, an AI story generation platform. The platform uses template-based prompts with XML-structured system/user prompt pairs to generate stories for specific platforms (Reddit, Reels, TikTok, YouTube, marketing).

The admin reviewer reading your analysis uses it to:
1. Understand exactly where and why the generated content falls short
2. Identify which parts of the prompt template need modification
3. Preserve prompt elements that are producing good results
4. Make targeted, evidence-based improvements to prompt engineering

Your review is NOT for the end user — it is an internal quality analysis tool for the team building and tuning the generation system.
</context>

<constraints>
- Score each rubric 1-10 with specific evidence from the text (quote exact phrases)
- Never give generic feedback like "could be better" — always specify WHAT and WHERE
- When identifying weaknesses, tie them back to likely prompt causes (e.g., "the role definition may be too generic" or "the constraints block is missing X")
- When identifying strengths, specify which prompt elements likely produced them
- Prompt suggestions must be specific enough to implement (e.g., "add to constraints: 'opening sentence must include specific ages'" not "make it more specific")
- Grade scale: A (exceptional, publishable as-is), B (strong with minor issues), C (adequate but needs work), D (significant problems), F (fundamental failures)
- Provide 3-5 weaknesses, 3-5 strengths, and 2-4 prompt suggestions
</constraints>

<expectation>
A successful review makes the admin say "I know exactly what to change in the prompt template." The descriptive analysis gives enough detail to understand the full picture. The crisp summary gives a quick reference for tracking quality trends across generations. The prompt suggestions are specific enough to copy-paste into the template JSON.

The review should feel like getting notes from a brilliant editor who also happens to understand how LLMs work — combining creative writing expertise with prompt engineering insight.
</expectation>`
}

// ========================================
// Review User Prompt
// ========================================

function buildReviewUserPrompt(params: ReviewOutputParams): string {
  return `<task>
Review and grade the following AI-generated story output on quality metrics. Provide both a detailed rubric-by-rubric analysis and a crisp summary.
</task>

<generation_context>
${params.templateName ? `Template: ${params.templateName}` : 'No template specified'}
</generation_context>

<story_seed>
${params.dreamscapeText}
</story_seed>

<system_prompt_used>
${params.systemPrompt}
</system_prompt_used>

<user_prompt_used>
${params.userPrompt}
</user_prompt_used>

<generated_output>
${params.outputText}
</generated_output>

<rubrics>
Assess the output on these 8 quality dimensions:

1. **Hook Effectiveness** — Does the opening grab attention immediately? Would a reader stop scrolling? Is the first line/paragraph compelling enough to earn the rest of the read?

2. **Narrative Authenticity** — Does this sound like a real person wrote it? Are there AI-ish patterns, clichés, or unnatural phrasings? Does the voice feel genuine for the target platform?

3. **Structural Cohesion** — Does the story hold together logically? Are there plot holes, inconsistencies, or unmotivated character actions? Does each beat flow naturally from the previous one?

4. **Pacing & Flow** — Is the story well-paced for its target length and platform? Are there sections that drag or rush? Does the rhythm serve the narrative?

5. **Twist/Surprise Factor** — Are there unexpected elements that feel earned (not forced)? Does the story subvert expectations in satisfying ways? Or is it predictable?

6. **Emotional Resonance** — Does the story evoke genuine feeling? Are the emotional beats earned through setup and character work, or do they feel manipulative/hollow?

7. **Platform Fit** — Does the content match the conventions, voice, and expectations of its target platform? Would it blend in with genuine platform content?

8. **Prompt Adherence** — How well does the output follow the constraints, tone, and structure defined in the system and user prompts? Are there deviations from what was asked?
</rubrics>

<output_format>
Provide your review in the structured format with:
- Detailed rubric analyses (2-4 sentences each with quoted evidence)
- Overall grade (A-F) and one-line verdict
- Crisp rubric scores
- Top weaknesses (tied to likely prompt causes)
- Top strengths (tied to which prompt elements produced them)
- Specific prompt modification suggestions
- Any additional notes valuable for admin review
</output_format>`
}

// ========================================
// Core Review Function
// ========================================

export async function reviewOutput(params: ReviewOutputParams): Promise<AIReviewResult> {
  const systemPrompt = buildReviewSystemPrompt()
  const userPrompt = buildReviewUserPrompt(params)

  const messages = [
    { role: 'system' as const, content: systemPrompt },
    { role: 'user' as const, content: userPrompt },
  ]

  const lt = startLangfuseGeneration('admin-review', messages, { temperature: 0.3 }, {
    model: 'gpt-5.4', metadata: { templateName: params.templateName },
  })

  const completion = await openai.beta.chat.completions.parse({
    model: 'gpt-5.4',
    messages,
    response_format: zodResponseFormat(ReviewResponseSchema, 'review'),
    temperature: 0.3, // Low temp for consistent, analytical output
  })

  await lt.end(completion)

  const result = completion.choices[0].message.parsed
  if (!result) {
    throw new Error('Failed to parse review response')
  }

  return result
}

export const reviewAdapter = {
  reviewOutput,
}
